version: '3.8'

services:
  web:
    build: ./Marketplace
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Marketplace/:/usr/src/Marketplace/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:8.0.21
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=t00r
      - MYSQL_USER=devil
      - MYSQL_PASSWORD=t00r
      - MYSQL_DATABASE=hello_django_dev
volumes:
  mysql_data:
