# Generated by Django 3.2.6 on 2021-12-26 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subs_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('name', models.CharField(max_length=200, null=True)),
                ('locations', models.CharField(choices=[('SlD', 'Select District'), ('Mrng', 'Morang'), ('Suns', 'Sunsari'), ('Ilm', 'Illam'), ('ktm', 'Kathmandu'), ('chtwn', 'Chitwan'), ('sirh', 'Siraha')], max_length=200, null=True)),
                ('listingcity', models.CharField(max_length=200)),
                ('phonnumber', models.IntegerField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, default='profiles/mehdi.png', null=True, upload_to='profiles/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
