# Generated by Django 3.2.6 on 2021-12-26 05:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Listingproducts',
            fields=[
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('isnegotiate', models.CharField(choices=[('yes', 'Yes'), ('fixedprice', 'Fixed price')], max_length=200, null=True)),
                ('adsexpiry', models.CharField(choices=[('TwoWeaks', 'Two Weaks'), ('1Months', 'One Months'), ('2Months', 'Two Months'), ('3Months', 'Three Months'), ('4Months', 'Four Months'), ('5Months', 'Five Months'), ('6Months', 'Six Months')], max_length=200, null=True)),
                ('deliverycharges', models.CharField(blank=True, max_length=200, null=True)),
                ('isdeliver', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=200, null=True)),
                ('deliveryarea', models.CharField(choices=[('withInMyArea', 'With in my Area'), ('withInMyCity', 'With in my City'), ('anywhere', 'Any where in Nepal')], max_length=200, null=True)),
                ('conditions', models.CharField(choices=[('LikeNew', 'Like New'), ('BrandNew', 'Brand New')], max_length=200, null=True)),
                ('userfor', models.CharField(blank=True, max_length=200, null=True)),
                ('descriptions', models.TextField(max_length=200, null=True)),
                ('featured_image', models.ImageField(default='default.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketapp.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersapp.userprofile')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketapp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ComputersFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processors', models.CharField(choices=[('pentium4', 'Intel Pentium 4'), ('pentiumDualCore', 'Intel Pentium Dual Core'), ('intelCeleron', 'Intel Celeron or Dual'), ('intelCorei3', 'Intel core i3'), ('intelCorei5', 'Intel core i5'), ('intelCorei7', 'Intel core i7'), ('intelCorei9', 'Intel core i9'), ('amdRyzen3', 'AMD Ryzen 3'), ('amdRyzen5', 'AMD Ryzen 5'), ('amdRyzen7', 'AMD Ryzen 7'), ('others', 'others')], max_length=200, null=True)),
                ('processorsgen', models.CharField(choices=[('donotknow', 'Donot Know'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th')], max_length=200, null=True)),
                ('memory', models.CharField(max_length=200, null=True)),
                ('storagetype', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('both', 'Both')], max_length=200, null=True)),
                ('storagegbtb', models.CharField(max_length=200, null=True)),
                ('listingproducts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.listingproducts')),
            ],
        ),
        migrations.CreateModel(
            name='AutovechFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotno', models.CharField(max_length=200, null=True)),
                ('enginecc', models.IntegerField(blank=True, null=True)),
                ('kilometersrun', models.IntegerField(blank=True, null=True)),
                ('makeyear', models.DateField(blank=True, null=True)),
                ('autoanchal', models.CharField(choices=[('koshi', 'Koshi'), ('mechi', 'Mechi'), ('bagmati', 'Bagmati'), ('sagarmatha', 'Sagarmatha'), ('lumbini', 'Lumbini'), ('gandaki', 'Gandaki'), ('janakpur', 'Janakpur'), ('mahakali', 'Mahakali'), ('karnali', 'Karnali'), ('narayani', 'Narayani'), ('rapti', 'Rapti'), ('seti', 'Seti'), ('bheri', 'Bheri'), ('dhawalagiri', 'Dhawalagiri')], max_length=200, null=True)),
                ('listingproducts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.listingproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersapp.userprofile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.listingproducts')),
            ],
            options={
                'unique_together': {('owner', 'project')},
            },
        ),
    ]
