# Generated by Django 3.2.6 on 2021-12-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_remove_userprofile_listingads'),
        ('marketapp', '0002_auto_20211229_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingproducts',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile', to='usersapp.userprofile'),
        ),
    ]
