# Generated by Django 3.2.6 on 2022-01-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_remove_userprofile_listingads'),
        ('marketapp', '0003_alter_listingproducts_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingproducts',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersapp.userprofile'),
        ),
    ]
