# Generated by Django 3.2.6 on 2022-01-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0004_alter_listingproducts_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingproducts',
            name='featured_image',
        ),
        migrations.CreateModel(
            name='ListingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(default='default.jpg', null=True, upload_to='')),
                ('listingproducts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.listingproducts')),
            ],
        ),
    ]
