# Generated by Django 3.2.6 on 2022-01-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0009_alter_listingimages_listingproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimages',
            name='listingproducts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketapp.listingproducts'),
        ),
    ]
