# Generated by Django 3.2.6 on 2022-01-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0011_auto_20220120_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='value',
        ),
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketapp.review'),
        ),
    ]
